# Generated by Django 5.2.5 on 2025-10-08 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_producto_rename_project_myapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.DeleteModel(
            name='myapp',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
